backend:
  name: github
  repo: mitchell-alt/heico-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Project Photos"
    folder: "images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
