backend:
  name: git-gateway
  branch: main

media_folder: "New folder/images"
public_folder: "/images"

collections:
  - label: "Project Gallery"
    name: "gallery"
    files:
      - label: "Projects"
        name: "projects"
        file: "New folder/gallery.json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Photo", name: "image", widget: "image" }
